### ISSUE TITLE
Add action name for example in README

### ISSUE THREAD

**Issue by eleni-salamani** [mablhq/github-run-tests-action#15]
Hi,

First of all, many thanks for providing an implementation for GitHub Actions!
We are currently evaluating mabl for our testing purposes and CI/CD integration is a basic requirement from our side.

I gave it a try and the [README](https://github.com/mablhq/github-run-tests-action/blob/v1.4/README.md) you are providing does not refer to the action someone in his/her own repository would include.
The correct format would be

```yaml
jobs:
  test:
    name: mabl Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Functional test deployment
        id: mabl-test-deployment
        **uses: mablhq/github-run-tests-action@v1.4**
        env:
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          application-id: 12345678
          environment-id: 9012344
```
instead of

```bash
**uses: ./deploy-and-test/**
```
Many thanks in advance,
Elena
